# Example config.yml

app:
  port: 5000
  nodeEnv: production
  name: Proof Generation API
  maticRPCs:
    - https://polygon-mainnet.g.alchemy.com/v2/afYQcl_4-oimsuqPRWV2naZUF1gdXIRs
    - https://polygon-mainnet.g.alchemy.com/v2/qiQZfrM2o-xX125sIij-AmhAkCxR1E-g
  ethereumRPCs:
    - https://eth-mainnet.g.alchemy.com/v2/tOFqeqwCfpkcg19ElpoKvQ5Z_W8u3F0p
    - https://eth-mainnet.g.alchemy.com/v2/Nr-dByMbi_ndnNv4Bz-2g-TrMdh0s8s-
  goerliRPC: https://eth-goerli.g.alchemy.com/v2/AaeN94mTHZhPsVCjZ51MuUyx9QiQ-zvP
  mumbaiRPC: https://polygon-mumbai.g.alchemy.com/v2/baZS_Upj4j4APoyt9jB3fZ4kEVGHkofN
